"""OpenAPI specification generation tests.

These tests ensure that the documentation generated by :mod:`backend.generate_openapi`
contains the newly added retention endpoints and the ``delete_on_read`` field
within the ``MessageRequest`` schema. Run with ``pytest``.
"""

import yaml
from backend.generate_openapi import build_spec


def test_openapi_retention_paths():
    """The spec should expose conversation and group retention paths."""
    spec = build_spec()
    data = yaml.safe_load(spec.to_yaml())
    paths = data.get("paths", {})
    assert "/api/conversations/{username}/retention" in paths
    assert "/api/groups/{group_id}/retention" in paths


def test_openapi_delete_on_read_field():
    """``MessageRequest`` must include ``delete_on_read`` property."""
    spec = build_spec()
    data = yaml.safe_load(spec.to_yaml())
    message_props = data["components"]["schemas"]["MessageRequest"]["properties"]
    assert "delete_on_read" in message_props
