name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  tls:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Verify TLS fingerprints
        shell: bash
        run: |
          set -e
          out=$(scripts/update_tls_fingerprints.sh --cert scripts/dev_cert.pem)
          fp_android=$(echo "$out" | grep ANDROID_FINGERPRINT | cut -d= -f2)
          fp_ios=$(echo "$out" | grep IOS_FINGERPRINT | cut -d= -f2)
          if ! grep -q "$fp_android" android/app/build.gradle; then
            echo 'Android fingerprint out of date' >&2
            exit 1
          fi
          if ! grep -q "$fp_ios" ios/PrivateLine/Resources/server_fingerprints.txt; then
            echo 'iOS fingerprints missing' >&2
            exit 1
          fi
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - run: pip install -r backend/requirements.txt
      - name: Generate OpenAPI spec
        run: python backend/generate_openapi.py
      - name: Verify OpenAPI spec committed
        run: git diff --exit-code docs/openapi.yaml
      - run: pytest

  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - run: npm ci
        working-directory: frontend
      - run: npm test --if-present
        working-directory: frontend

  ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15'
      - name: Run iOS tests
        run: xcodebuild -scheme PrivateLine-Package -destination 'platform=iOS Simulator,name=iPhone 14' test
        working-directory: ios

  android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Generate wrapper JAR
        run: gradle wrapper
        working-directory: android
      - name: Build Android project
        run: ./gradlew assembleDebug
        working-directory: android
